spring:
  application:
    name: flight-booking-backend
  
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/JavaFullStackTraining}
    username: ${DB_USERNAME:JavaFullStackTrainingAdmin}
    password: ${DB_PASSWORD:8xchWheZpKiiQxnX}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    show-sql: ${DB_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours

logging:
  level:
    com.flightbooking: ${LOG_LEVEL:DEBUG}
    org.springframework.security: ${LOG_LEVEL:DEBUG} 